#make the examples
all: anF ax axM cosm 

anF:
	cd AnharmonicFactor && $(MAKE)

ax:
	cd Axion && $(MAKE)

axM:
	cd AxionMass && $(MAKE)

cosm:
	cd Cosmo && $(MAKE)

clean:
	rm -f AnharmonicFactor/*.run
	rm -f Axion/*.run
	rm -f AxionMass/*.run
	rm -f Cosmo/*.run
